default_language_version:
    python: python3
repos:
  - repo: https://github.com/psf/black
    rev: 26.3.1
    hooks:
      - id: black
  - repo: https://github.com/python-poetry/poetry
    rev: "2.3.4"
    hooks:
      - id: poetry-check # Makes sure poetry config is valid
      - id: poetry-lock # Makes sure lock file is up to date
        args: ["--check"]
  - repo: https://github.com/PyCQA/bandit
    rev: "1.9.4"
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]
        exclude: notebooks
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.20.2"
    hooks:
      - id: mypy
        args: ["--ignore-missing-imports", "--strict", "--check-untyped-defs"]
        additional_dependencies: ["click>=8.1.8,<9.0.0", "numpy>=1.24.3,<3.0.0", "pytest>=8.4,<10.0", "types-requests>=2.33.0.20260408,<3.0.0"]
        exclude: notebooks

